---
- name: Install python
  yum:
    name: python
    state: latest

- name: Create Downloads directory
  file:
    path: "{{ ansible_env.HOME }}/Downloads"
    state: directory

- name: Download get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: "{{ ansible_env.HOME }}/Downloads"

- name: Install pip
  command: "/usr/bin/python {{ ansible_env.HOME }}/Downloads/get-pip.py"

- name: Install selenium-python
  pip:
    name: selenium
    state: latest
