---
- name: Install Ruby and other dependencies
  yum:
    name: 
      - ruby
      - rubygems
      - ruby-devel
      - gcc
    state: latest

- name: Install selenium-ruby
  gem:
    name: selenium-webdriver
    state: latest
